services:
  user_service_db:
    container_name: user_service_db
    restart: always
    image: postgres:17.6-alpine
    volumes:
      - user-service-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${USER_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_USER=${USER_SERVICE_POSTGRES_LOGIN}
      - POSTGRES_DB=${USER_SERVICE_POSTGRES_DB_NAME}
    expose:
      - "${USER_SERVICE_POSTGRES_DB_PORT}"
    command: -p ${USER_SERVICE_POSTGRES_DB_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${USER_SERVICE_POSTGRES_LOGIN} -d ${USER_SERVICE_POSTGRES_DB_NAME} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - app-net
  user_service:
    build:
      context: ./services/users_service
      dockerfile: Dockerfile
    container_name: user_service
    restart: unless-stopped
    expose:
      - ${USER_SERVICE_PORT}
    environment:
      - PORT=${USER_SERVICE_PORT}
      - DB_URL=${USER_SERVICE_POSTGRES_URL}
    networks:
      - app-net
    depends_on:
      user_service_db:
        condition: service_healthy

networks:
  app-net:
    driver: bridge

volumes:
  user-service-pgdata:
